package io.quarkiverse.fx.deployment;

public interface FxClassesAndResources {
    String[] RUNTIME_INITIALIZED_CLASS_SUFFIXES = {
            "$StyleableProperties"
    };
    String[] RUNTIME_INITIALIZED_CLASSES = {
            "javafx.scene.CssStyleHelper",
            "javafx.scene.Node",
            "javafx.scene.control.ListView$EditEvent",
            "javafx.scene.control.PopupControl",
            "javafx.scene.control.SkinBase",
            "javafx.scene.control.TreeTableView$EditEvent",
            "javafx.scene.control.TreeView$EditEvent",
            "javafx.scene.control.skin.ColorPickerSkin",
            "javafx.scene.control.skin.MenuBarSkin",
            "javafx.scene.control.skin.ProgressIndicatorSkin",
            "javafx.scene.control.skin.TableRowSkinBase",
            "javafx.scene.control.skin.TextInputControlSkin",
            "javafx.scene.control.skin.MenuButtonSkin",
            "javafx.scene.image.Image",
            "javafx.scene.image.WritableImage",
            "javafx.scene.layout.Background",
            "javafx.scene.paint.Color$NamedColors",
            "javafx.scene.paint.Paint",
            "javafx.scene.paint.Stop",
            "javafx.scene.web.WebEngine",
            "javafx.scene.web.WebEngine$PulseTimer",
            "javafx.stage.Screen",
            "com.sun.glass.ui.Clipboard",
            "com.sun.glass.ui.win.WinAccessible",
            "com.sun.glass.ui.win.WinApplication",
            "com.sun.glass.ui.win.WinCommonDialogs",
            "com.sun.glass.ui.win.WinCursor",
            "com.sun.glass.ui.win.WinGestureSupport",
            "com.sun.glass.ui.win.WinMenuImpl",
            "com.sun.glass.ui.win.WinPixels",
            "com.sun.glass.ui.win.WinTextRangeProvider",
            "com.sun.glass.ui.win.WinTimer",
            "com.sun.glass.ui.win.WinWindow",
            "com.sun.glass.ui.win.WinView",
            "com.sun.glass.ui.gtk.GtkApplication",
            "com.sun.glass.utils.NativeLibLoader",
            "com.sun.glass.utils.ModuleHelper",
            "com.sun.javafx.application.LauncherImpl",
            "com.sun.javafx.application.PlatformImpl",
            "com.sun.javafx.font.AndroidFontFinder",
            "com.sun.javafx.font.DFontDecoder",
            "com.sun.javafx.font.MacFontFinder",
            "com.sun.javafx.font.PrismFontFactory",
            "com.sun.javafx.font.PrismFontFile",
            "com.sun.javafx.font.directwrite.DWFontStrike",
            "com.sun.javafx.font.directwrite.OS",
            "com.sun.javafx.fxml.ModuleHelper",
            "com.sun.javafx.iio.jpeg.JPEGImageLoader",
            "com.sun.javafx.scene.control.LabeledHelper",
            "com.sun.javafx.scene.control.Properties",
            "com.sun.javafx.scene.control.behavior.TextInputControlBehavior",
            "com.sun.javafx.scene.control.skin.FXVKSkin",
            "com.sun.javafx.scene.control.skin.Utils",
            "com.sun.javafx.scene.text.TextFlowHelper",
            "com.sun.javafx.scene.traversal.TraversalEngine",
            "com.sun.javafx.scene.NodeHelper",
            "com.sun.javafx.text.GlyphLayoutManager",
            "com.sun.javafx.text.PrismTextLayoutFactory",
            "com.sun.javafx.tk.Toolkit",
            "com.sun.javafx.tk.quantum.PaintCollector",
            "com.sun.javafx.tk.quantum.PrismImageLoader2$AsyncImageLoader",
            "com.sun.javafx.webkit.prism.PrismGraphicsManager",
            "com.sun.marlin.DMarlinRenderingEngine",
            "com.sun.marlin.MarlinUtils",
            "com.sun.marlin.MaskMarlinAlphaConsumer",
            "com.sun.prism.PresentableState",
            "com.sun.prism.GraphicsPipeline",
            "com.sun.prism.d3d.D3DPipeline",
            "com.sun.prism.es2.ES2Pipeline",
            "com.sun.prism.impl.BaseResourcePool",
            "com.sun.prism.impl.PrismSettings",
            "com.sun.prism.impl.ps.PaintHelper",
            "com.sun.prism.sw.SWPipeline",
            "com.sun.scenario.animation.AbstractPrimaryTimer",
            "com.sun.webkit.WCWidget",
            "com.sun.webkit.WCWidget",
            "com.sun.webkit.WebPage",
    };

    String[] REFLECTIVE_ROOT_CLASSES = {
            "javafx.stage.Window",
            "javafx.scene.control.Dialog",
            "javafx.scene.Node",
            "javafx.scene.shape.PathElement",
            "javafx.scene.shape.Mesh",
            "javafx.scene.paint.Paint",
            "javafx.scene.paint.Material",
            "javafx.scene.image.Image",
            "javafx.scene.effect.Effect",
            "javafx.scene.transform.Transform",
            "javafx.scene.layout.ConstraintsBase",
            "javafx.scene.input.Clipboard",
            "com.sun.glass.ui.Application",
            "com.sun.glass.ui.Clipboard",
            "com.sun.glass.ui.Cursor",
            "com.sun.glass.ui.Pixels",
            "com.sun.glass.ui.PlatformFactory",
            "com.sun.glass.ui.View",
            "com.sun.glass.ui.Window",
            "com.sun.scenario.effect.Effect",
            "com.sun.scenario.effect.impl.EffectPeer",
            "com.sun.scenario.effect.impl.Renderer",
            "com.sun.prism.GraphicsPipeline",
    };

    String[] REFLECTIVE_INTERFACES = {
            "javafx.event.Event",
            "javafx.css.Styleable",
            "com.sun.scenario.effect.impl.hw.ShaderSource",
    };

    String[] REFLECTIVE_PACKAGES = {
            "com.sun.prism.shader",
    };

    String[] REFLECTIVE_CLASSES = {
            "java.nio.ByteBuffer",
            "java.nio.ByteOrder",
            "javafx.scene.control.ButtonType",
            "javafx.scene.text.Font",
            "javafx.css.Rule",
            "javafx.scene.input.TouchPoint",
            "javafx.animation.KeyFrame",
            "javafx.animation.KeyValue",

            // all enums that can be used in FXML
            "javafx.geometry.Pos",
            "javafx.geometry.HPos",
            "javafx.geometry.VPos",
            "javafx.geometry.Insets",
            "javafx.geometry.Orientation",
            "javafx.geometry.NodeOrientation",
            "javafx.geometry.Side",
            "javafx.scene.text.TextAlignment",
            "javafx.scene.text.FontSmoothingType",
            "javafx.scene.text.FontPosture",
            "javafx.scene.text.FontWeight",
            "javafx.scene.text.TextBoundsType",
            "javafx.css.SizeUnits",
            "javafx.css.StyleOrigin",
            "javafx.scene.effect.BlurType",
            "javafx.scene.input.MouseButton",
            "javafx.scene.layout.Priority",
            "javafx.scene.shape.StrokeType",
            "javafx.scene.control.TabPane$TabClosingPolicy",
            "javafx.scene.control.TabPane$TabDragPolicy",
            "javafx.scene.control.ScrollPane$ScrollBarPolicy",
            "javafx.scene.control.Alert$AlertType",
            "javafx.scene.control.ButtonBar$ButtonData",
            // TODO: add more

            "com.sun.pisces.Transform6",
            "com.sun.pisces.PiscesRenderer",
            "com.sun.pisces.JavaSurface",
            "com.sun.pisces.AbstractSurface",
            "com.sun.prism.impl.PrismSettings",

            "com.sun.javafx.tk.quantum.QuantumToolkit",
            "com.sun.javafx.scene.control.skin.Utils",
            "com.sun.javafx.reflect.Trampoline",
            "com.sun.javafx.logging.jfr.JFRPulseLogger",
            "com.sun.javafx.logging.PrintLogger",
            "com.sun.javafx.geom.Path2D",
            "com.sun.javafx.fxml.builder.JavaFXSceneBuilder",
            "com.sun.javafx.font.directwrite.D2D1_COLOR_F",
            "com.sun.javafx.font.directwrite.D2D1_MATRIX_3X2_F",
            "com.sun.javafx.font.directwrite.D2D1_PIXEL_FORMAT",
            "com.sun.javafx.font.directwrite.D2D1_POINT_2F",
            "com.sun.javafx.font.directwrite.D2D1_RENDER_TARGET_PROPERTIES",
            "com.sun.javafx.font.directwrite.DWFactory",
            "com.sun.javafx.font.directwrite.DWRITE_GLYPH_METRICS",
            "com.sun.javafx.font.directwrite.DWRITE_GLYPH_RUN",
            "com.sun.javafx.font.directwrite.DWRITE_MATRIX",
            "com.sun.javafx.font.directwrite.DWRITE_SCRIPT_ANALYSIS",
            "com.sun.javafx.font.directwrite.RECT",
            "com.sun.javafx.PreviewFeature",
            "com.sun.glass.ui.CommonDialogs$ExtensionFilter",
            "com.sun.glass.ui.CommonDialogs$FileChooserResult",
            "com.sun.glass.ui.EventLoop",
            "com.sun.glass.ui.Size",
            "com.sun.glass.ui.Screen",
            "com.sun.scenario.effect.impl.Renderer",
            "com.sun.scenario.effect.impl.sw.sse.SSERendererDelegate",

            "io.quarkiverse.fx.FxApplication",
            "io.quarkiverse.fx.views.FxViewConfig$$CMImpl",
            "io.quarkiverse.fx.FXMLLoaderProducer",
            "io.quarkiverse.fx.FxApplicationStartupEvent",
            "io.quarkiverse.fx.FxPostStartupEvent",
            "io.quarkiverse.fx.FxStartupLatch",
            "io.quarkiverse.fx.FxViewLoadEvent",
            "io.quarkiverse.fx.HostServicesProducer",
            "io.quarkiverse.fx.views.FxViewConfig",
            "io.quarkiverse.fx.views.FxViewRepository",
    };

    String[] WINDOWS_REFLECTIVE_CLASSES = {
            "com.sun.glass.ui.win.WinDnDClipboard",
            "com.sun.glass.ui.win.WinGestureSupport",
            "com.sun.glass.ui.win.WinPlatformFactory",
            "com.sun.javafx.font.directwrite.DWFactory",
            "com.sun.prism.d3d.D3DDriverInformation",
            "com.sun.prism.d3d.D3DPipeline",
            "com.sun.prism.d3d.D3DResourceFactory",
            "com.sun.prism.d3d.D3DShader",
            "com.sun.scenario.effect.impl.hw.d3d.D3DShaderSource",
    };

    String[] MAC_REFLECTIVE_CLASSES = {
            "com.sun.prism.es2.ES2Pipeline",
            "com.sun.prism.es2.ES2PhongShader",
            "com.sun.prism.es2.ES2ResourceFactory",
            "com.sun.prism.es2.ES2Shader",
            "com.sun.prism.es2.MacGLFactory",
            "com.sun.scenario.effect.impl.es2.ES2ShaderSource",
            "com.sun.glass.ui.mac.MacApplication",
            "com.sun.glass.ui.mac.MacPixels",
            "com.sun.glass.ui.mac.MacView",
            "com.sun.glass.ui.mac.MacPlatformFactory",
            "com.sun.glass.ui.mac.MacGestureSupport",
            "com.sun.glass.ui.mac.MacMenuBarDelegate",
            "com.sun.glass.ui.mac.MacCommonDialogs",
            "com.sun.glass.ui.mac.MacFileNSURL",
            "com.sun.javafx.font.coretext.CTFactory",
    };

    String[] LINUX_REFLECTIVE_CLASSES = {
            "com.sun.prism.es2.MonocleGLFactory",
            "com.sun.prism.es2.ES2Pipeline",
            "com.sun.prism.es2.ES2PhongShader",
            "com.sun.prism.es2.ES2ResourceFactory",
            "com.sun.prism.es2.ES2Shader",
            "com.sun.prism.es2.X11GLFactory",
            "com.sun.scenario.effect.impl.es2.ES2ShaderSource",
            "com.sun.glass.ui.gtk.GtkPlatformFactory",
            "com.sun.glass.ui.monocle.EGLPlatformFactory",
            "com.sun.glass.ui.monocle.MonoclePlatformFactory",
            "com.sun.javafx.font.freetype.FTFactory",
    };

    String[] JNI_RUNTIME_ACCESS_CLASSES = {
            "java.lang.Boolean",
            "java.lang.Class",
            "java.lang.Iterable",
            "java.lang.Object",
            "java.lang.Runnable",
            "java.lang.String",
            "java.lang.Throwable",
            "java.util.ArrayList",
            "java.util.Collections",
            "java.util.Iterator",
            "java.util.HashMap",
            "java.util.HashSet",
            "java.util.Map",
            "java.util.Set",
            "java.nio.ByteBuffer",
            "javafx.scene.paint.Color",
            "com.sun.prism.d3d.D3DDriverInformation",
            "com.sun.prism.impl.PrismSettings",
            "com.sun.glass.ui.Application",
            "com.sun.glass.ui.Clipboard",
            "com.sun.glass.ui.Cursor",
            "com.sun.glass.ui.Menu",
            "com.sun.glass.ui.MenuItem$Callback",
            "com.sun.glass.ui.Pixels",
            "com.sun.glass.ui.Screen",
            "com.sun.glass.ui.Size",
            "com.sun.glass.ui.View",
            "com.sun.glass.ui.Window",
            "com.sun.javafx.geom.Path2D",
            "com.sun.glass.ui.CommonDialogs",
            "com.sun.glass.ui.CommonDialogs$ExtensionFilter",
            "com.sun.glass.ui.CommonDialogs$FileChooserResult",
            "com.sun.glass.ui.EventLoop",
            "com.sun.javafx.font.FontConfigManager$FcCompFont",
            "com.sun.javafx.font.FontConfigManager$FontConfigFont",
            "com.sun.javafx.iio.jpeg.JPEGImageLoader",
            "com.sun.javafx.iio.common.ImageLoaderImpl",
            "com.sun.pisces.Transform6",
            "com.sun.pisces.PiscesRenderer",
            "com.sun.pisces.JavaSurface",
            "com.sun.pisces.AbstractSurface",
    };
    String[] WINDOWS_JNI_RUNTIME_ACCESS_CLASSES = {
            "com.sun.glass.ui.win.WinApplication",
            "com.sun.glass.ui.win.WinDnDClipboard",
            "com.sun.glass.ui.win.WinGestureSupport",
            "com.sun.glass.ui.win.WinPixels",
            "com.sun.glass.ui.win.WinSystemClipboard",
            "com.sun.glass.ui.win.WinView",
            "com.sun.glass.ui.win.WinWindow",
            "com.sun.javafx.font.directwrite.D2D1_COLOR_F",
            "com.sun.javafx.font.directwrite.D2D1_MATRIX_3X2_F",
            "com.sun.javafx.font.directwrite.D2D1_PIXEL_FORMAT",
            "com.sun.javafx.font.directwrite.D2D1_POINT_2F",
            "com.sun.javafx.font.directwrite.D2D1_RENDER_TARGET_PROPERTIES",
            "com.sun.javafx.font.directwrite.DWRITE_GLYPH_METRICS",
            "com.sun.javafx.font.directwrite.DWRITE_GLYPH_RUN",
            "com.sun.javafx.font.directwrite.DWRITE_MATRIX",
            "com.sun.javafx.font.directwrite.DWRITE_SCRIPT_ANALYSIS",
            "com.sun.javafx.font.directwrite.RECT",
    };
    String[] MAC_JNI_RUNTIME_ACCESS_CLASSES = {
            "com.sun.glass.ui.mac.MacAccessible",
            "com.sun.glass.ui.mac.MacAccessible$MacAction",
            "com.sun.glass.ui.mac.MacAccessible$MacAttribute",
            "com.sun.glass.ui.mac.MacAccessible$MacNotification",
            "com.sun.glass.ui.mac.MacAccessible$MacOrientation",
            "com.sun.glass.ui.mac.MacAccessible$MacRole",
            "com.sun.glass.ui.mac.MacAccessible$MacSubrole",
            "com.sun.glass.ui.mac.MacAccessible$MacText",
            "com.sun.glass.ui.mac.MacVariant",
            "com.sun.glass.ui.mac.MacApplication",
            "com.sun.glass.ui.mac.MacCommonDialogs",
            "com.sun.glass.ui.mac.MacCursor",
            "com.sun.glass.ui.mac.MacGestureSupport",
            "com.sun.glass.ui.mac.MacMenuBarDelegate",
            "com.sun.glass.ui.mac.MacMenuDelegate",
            "com.sun.glass.ui.mac.MacView",
            "com.sun.glass.ui.mac.MacWindow",
            "com.sun.javafx.font.coretext.CGAffineTransform",
            "com.sun.javafx.font.coretext.CGPoint",
            "com.sun.javafx.font.coretext.CGRect",
            "com.sun.javafx.font.coretext.CGSize",

    };
    String[] LINUX_JNI_RUNTIME_ACCESS_CLASSES = {
            "com.sun.glass.ui.gtk.GtkApplication",
            "com.sun.glass.ui.gtk.GtkPixels",
            "com.sun.glass.ui.gtk.GtkView",
            "com.sun.glass.ui.gtk.GtkWindow",
            "com.sun.javafx.font.freetype.FT_Bitmap",
            "com.sun.javafx.font.freetype.FT_GlyphSlotRec",
            "com.sun.javafx.font.freetype.FT_Glyph_Metrics",
            "com.sun.javafx.font.freetype.FT_Matrix",
            "com.sun.javafx.font.freetype.PangoGlyphString",
    };

    String[] RESOURCE_BUNDLES = {
            "com.sun.javafx.scene.control.skin.resources.controls",
            "com.sun.javafx.tk.quantum.QuantumMessagesBundle",
    };

    String[] WINDOWS_RESOURCE_BUNDLES = {
            "com.sun.glass.ui.win.themes",
    };

    String[] RESOURCE_GLOBS = {
            "META-INF/fonts.mf",
            "com/sun/javafx/scene/control/skin/modena/**",
            "com/sun/prism/d3d/hlsl/**",
            "com/sun/scenario/effect/impl/hw/d3d/hlsl/**",

            // .jar files in javafx-graphics
            "javafx-swt.jar",
    };

    String[] WINDOWS_RESOURCE_GLOBS = {
            // Windows .dll files in javafx-graphics
            "api-ms-win-core-*.dll",
            "api-ms-win-crt-*.dll",
            "decora_sse.dll",
            "glass.dll",
            "javafx_font.dll",
            "javafx_iio.dll",
            "msvcp*.dll",
            "prism_*.dll",
            "ucrtbase.dll",
            "vcruntime*.dll",

            // Windows .dll files in javafx-media
            "fxplugins.dll",
            "glib-lite.dll",
            "gstreamer-lite.dll",
            "jfxmedia.dll",

            // Windows .dll files in javafx-web
            "jfxwebkit.dll",
    };

    String[] MAC_RESOURCE_GLOBS = {
            // Mac .dylib files in javafx-graphics
            "libdecora_sse.dylib",
            "libglass.dylib",
            "libjavafx_font.dylib",
            "libjavafx_iio.dylib",
            "libprism_common.dylib",
            "libprism_es2.dylib",
            "libprism_sw.dylib",

            // Mac .dylib files in javafx-media
            "libfxplugins.dylib",
            "libglib-lite.dylib",
            "libgstreamer-lite.dylib",
            "libjfxmedia.dylib",
            "libjfxmedia_avf.dylib",

            // Mac .dylib files in javafx-media
            "libjfxwebkit.dylib",
    };

    String[] LINUX_RESOURCE_GLOBS = {
            // Linux .so files in javafx-graphics
            "libdecora_sse.so",
            "libglass.so",
            "libglassgtk3.so",
            "libjavafx_font.so",
            "libjavafx_font_freetype.so",
            "libjavafx_font_pango.so",
            "libjavafx_iio.so",
            "libprism_common.so",
            "libprism_es2.so",
            "libprism_sw.so",

            // Linux .so files in javafx-media
            "libavplugin-*.so",
            "libavplugin-ffmpeg-*.so",
            "libfxplugins.so",
            "libgstreamer-lite.so",
            "libjfxmedia.so",

            // Linux .so files in javafx-web
            "libjfxwebkit.so",
    };
}
