package io.quarkiverse.fx.deployment;

public interface FxClassesAndResources {
    String[] RUNTIME_INITIALIZED_CLASSES = new String[] {
            "javafx.scene.Node",
            "javafx.scene.chart.Axis$StyleableProperties",
            "javafx.scene.chart.NumberAxis$StyleableProperties",
            "javafx.scene.chart.ValueAxis$StyleableProperties",
            "javafx.scene.control.Control$StyleableProperties",
            "javafx.scene.control.DialogPane$StyleableProperties",
            "javafx.scene.control.Labeled$StyleableProperties",
            "javafx.scene.control.ListView$EditEvent",
            "javafx.scene.control.ListView$StyleableProperties",
            "javafx.scene.control.PopupControl",
            "javafx.scene.control.ScrollBar$StyleableProperties",
            "javafx.scene.control.ScrollPane$StyleableProperties",
            "javafx.scene.control.Separator$StyleableProperties",
            "javafx.scene.control.SkinBase$StyleableProperties",
            "javafx.scene.control.Slider$StyleableProperties",
            "javafx.scene.control.SplitPane$StyleableProperties",
            "javafx.scene.control.TabPane$StyleableProperties",
            "javafx.scene.control.TextArea$StyleableProperties",
            "javafx.scene.control.TextField$StyleableProperties",
            "javafx.scene.control.TextInputControl$StyleableProperties",
            "javafx.scene.control.TitledPane$StyleableProperties",
            "javafx.scene.control.skin.CellSkinBase$StyleableProperties",
            "javafx.scene.control.skin.ProgressBarSkin$StyleableProperties",
            "javafx.scene.control.skin.ProgressIndicatorSkin",
            "javafx.scene.control.skin.TabPaneSkin$StyleableProperties",
            "javafx.scene.control.skin.TextInputControlSkin",
            "javafx.scene.control.skin.TextInputControlSkin$StyleableProperties",
            "javafx.stage.Screen",
            "javafx.scene.CssStyleHelper",
            "javafx.scene.image.ImageView$StyleableProperties",
            "javafx.scene.layout.GridPane$StyleableProperties",
            "javafx.scene.layout.HBox$StyleableProperties",
            "javafx.scene.layout.Region$StyleableProperties",
            "javafx.scene.layout.StackPane$StyleableProperties",
            "javafx.scene.layout.VBox$StyleableProperties",
            "javafx.scene.shape.Rectangle$StyleableProperties",
            "javafx.scene.shape.Shape$StyleableProperties",
            "javafx.scene.text.Text$StyleableProperties",
            "javafx.scene.web.WebEngine",
            "javafx.scene.web.WebEngine$PulseTimer",
            "javafx.scene.web.WebView$StyleableProperties",
            "com.sun.glass.ui.Clipboard",
            "com.sun.glass.ui.win.WinAccessible",
            "com.sun.glass.ui.win.WinApplication",
            "com.sun.glass.ui.win.WinCommonDialogs",
            "com.sun.glass.ui.win.WinCursor",
            "com.sun.glass.ui.win.WinGestureSupport",
            "com.sun.glass.ui.win.WinMenuImpl",
            "com.sun.glass.ui.win.WinPixels",
            "com.sun.glass.ui.win.WinTimer",
            "com.sun.glass.ui.win.WinWindow",
            "com.sun.glass.ui.win.WinView",
            "com.sun.javafx.font.AndroidFontFinder",
            "com.sun.javafx.font.DFontDecoder",
            "com.sun.javafx.font.MacFontFinder",
            "com.sun.javafx.font.PrismFontFactory",
            "com.sun.javafx.font.PrismFontFile",
            "com.sun.javafx.font.directwrite.DWFontStrike",
            "com.sun.javafx.font.directwrite.OS",
            "com.sun.javafx.iio.jpeg.JPEGImageLoader",
            "com.sun.javafx.scene.control.ContextMenuContent$StyleableProperties",
            "com.sun.javafx.scene.control.LabeledHelper",
            "com.sun.javafx.scene.control.LabeledImpl$StyleableProperties",
            "com.sun.javafx.scene.control.Properties",
            "com.sun.javafx.scene.control.behavior.TextInputControlBehavior",
            "com.sun.javafx.scene.control.skin.FXVKSkin",
            "com.sun.javafx.scene.control.skin.Utils",
            "com.sun.javafx.scene.NodeHelper",
            "com.sun.javafx.text.GlyphLayoutManager",
            "com.sun.javafx.text.PrismTextLayoutFactory",
            "com.sun.javafx.tk.quantum.PrismImageLoader2$AsyncImageLoader",
            "com.sun.javafx.webkit.prism.PrismGraphicsManager",
            "com.sun.marlin.DMarlinRenderingEngine",
            "com.sun.marlin.MarlinUtils",
            "com.sun.marlin.MaskMarlinAlphaConsumer",
            "com.sun.prism.PresentableState",
            "com.sun.prism.d3d.D3DPipeline",
            "com.sun.prism.es2.ES2Pipeline",
            "com.sun.prism.impl.BaseResourcePool",
            "com.sun.prism.impl.PrismSettings",
            "com.sun.prism.impl.ps.PaintHelper",
            "com.sun.prism.sw.SWPipeline",
            "com.sun.scenario.animation.AbstractPrimaryTimer",
            "com.sun.webkit.WCWidget",
            "com.sun.webkit.WCWidget",
            "com.sun.webkit.WebPage",
    };

    String[] REFLECTIVE_CLASSES = new String[] {
            "javafx.stage.Stage",
            "javafx.stage.Window",
            "javafx.scene.paint.Color",
            "javafx.scene.layout.VBox",
            "javafx.scene.layout.StackPane",
            "javafx.scene.layout.Region",
            "javafx.scene.layout.Priority",
            "javafx.scene.layout.Pane",
            "javafx.scene.layout.HeaderBar",
            "javafx.scene.layout.HBox",
            "javafx.scene.layout.GridPane",
            "javafx.scene.layout.FontIcon",
            "javafx.scene.layout.ConstraintsBase",
            "javafx.scene.layout.ColumnConstraints",
            "javafx.scene.layout.BorderPane",
            "javafx.scene.image.ImageView",
            "javafx.scene.control.ToggleButton",
            "javafx.scene.control.TitledPane",
            "javafx.scene.control.TextInputControl",
            "javafx.scene.control.TextField",
            "javafx.scene.control.TextArea",
            "javafx.scene.control.TabPane$TabClosingPolicy",
            "javafx.scene.control.TabPane",
            "javafx.scene.control.Tab",
            "javafx.scene.control.SplitPane",
            "javafx.scene.control.Slider",
            "javafx.scene.control.Separator",
            "javafx.scene.control.ScrollPane$ScrollBarPolicy",
            "javafx.scene.control.ScrollPane",
            "javafx.scene.control.ProgressIndicator",
            "javafx.scene.control.ProgressBar",
            "javafx.scene.control.MenuItem",
            "javafx.scene.control.MenuButton",
            "javafx.scene.control.ListView",
            "javafx.scene.control.Labeled",
            "javafx.scene.control.Label",
            "javafx.scene.control.DialogPane",
            "javafx.scene.control.Dialog",
            "javafx.scene.control.ComboBox",
            "javafx.scene.control.ButtonBase",
            "javafx.scene.control.Button",
            "javafx.scene.control.Alert",
            "javafx.scene.Parent",
            "javafx.scene.Node",
            "javafx.geometry.VPos",
            "javafx.geometry.Pos",
            "javafx.geometry.Orientation",
            "javafx.geometry.NodeOrientation",
            "javafx.geometry.Insets",
            "javafx.geometry.HPos",

            "javafx.stage.PopupWindow",
            "javafx.scene.web.WebView",
            "javafx.scene.transform.Transform",
            "javafx.scene.text.Text",
            "javafx.scene.text.Font",
            "javafx.scene.shape.Shape",
            "javafx.scene.shape.SVGPath",
            "javafx.scene.shape.Rectangle",
            "javafx.scene.shape.PathElement",
            "javafx.scene.shape.Path",
            "javafx.scene.shape.MoveTo",
            "javafx.scene.shape.LineTo",
            "javafx.scene.image.Image",
            "javafx.scene.effect.Effect",
            "javafx.scene.control.VBox",
            "javafx.scene.control.StackPane",
            "javafx.scene.control.HBox",
            "javafx.scene.control.GridPane",
            "javafx.scene.control.FontIcon",
            "javafx.scene.control.Control",
            "javafx.scene.control.ComboBoxBase",
            "javafx.scene.control.BorderPane",
            "javafx.scene.ParallelCamera",
            "javafx.scene.Group",
            "javafx.scene.Camera",
            "javafx.fxml.FXMLLoader",
            "javafx.event.EventTarget",
            "javafx.css.Rule",
            "javafx.concurrent.Worker",
            "javafx.concurrent.Task",
            "javafx.application.HostServices",
            "javafx.animation.KeyValue",
            "javafx.animation.Interpolator",

            "com.sun.scenario.effect.impl.prism.ps.PPSRenderer",
            "com.sun.scenario.effect.impl.prism.ps.PPSLinearConvolveShadowPeer",
            "com.sun.scenario.effect.impl.prism.ps.PPSBlend_SRC_INPeer",
            "com.sun.scenario.effect.impl.prism.PrRenderer",
            "com.sun.scenario.effect.impl.hw.d3d.D3DShaderSource",
            "com.sun.prism.shader.Texture_LinearGradient_PAD_Loader",
            "com.sun.prism.shader.Texture_Color_Loader",
            "com.sun.prism.shader.Solid_TextureSecondPassLCD_Loader",
            "com.sun.prism.shader.Solid_TextureRGB_Loader",
            "com.sun.prism.shader.Solid_TextureFirstPassLCD_Loader",
            "com.sun.prism.shader.Solid_Color_Loader",
            "com.sun.prism.shader.FillRoundRect_LinearGradient_PAD_Loader",
            "com.sun.prism.shader.FillRoundRect_Color_Loader",
            "com.sun.prism.shader.FillPgram_LinearGradient_PAD_Loader",
            "com.sun.prism.shader.FillPgram_Color_Loader",
            "com.sun.prism.shader.DrawRoundRect_Color_Loader",
            "com.sun.prism.shader.DrawPgram_Color_Loader",
            "com.sun.prism.impl.PrismSettings",
            "com.sun.prism.sw.SWPipeline",
            "com.sun.prism.d3d.D3DPipeline",
            "com.sun.prism.GraphicsPipeline",
            "com.sun.javafx.tk.quantum.QuantumToolkit",
            "com.sun.javafx.scene.control.skin.Utils",
            "com.sun.javafx.reflect.Trampoline",
            "com.sun.javafx.logging.jfr.JFRPulseLogger",
            "com.sun.javafx.logging.PrintLogger",
            "com.sun.javafx.fxml.builder.JavaFXSceneBuilder",
            "com.sun.javafx.font.directwrite.RECT",
            "com.sun.javafx.font.directwrite.DWRITE_SCRIPT_ANALYSIS",
            "com.sun.javafx.font.directwrite.DWRITE_MATRIX",
            "com.sun.javafx.font.directwrite.DWRITE_GLYPH_RUN",
            "com.sun.javafx.font.directwrite.DWRITE_GLYPH_METRICS",
            "com.sun.javafx.font.directwrite.DWFactory",
            "com.sun.javafx.font.directwrite.D2D1_RENDER_TARGET_PROPERTIES",
            "com.sun.javafx.font.directwrite.D2D1_POINT_2F",
            "com.sun.javafx.font.directwrite.D2D1_PIXEL_FORMAT",
            "com.sun.javafx.font.directwrite.D2D1_MATRIX_3X2_F",
            "com.sun.javafx.font.directwrite.D2D1_COLOR_F",
            "com.sun.glass.ui.win.WinWindow",
            "com.sun.glass.ui.win.WinView",
            "com.sun.glass.ui.win.WinSystemClipboard",
            "com.sun.glass.ui.win.WinPlatformFactory",
            "com.sun.glass.ui.win.WinGestureSupport",
            "com.sun.glass.ui.win.WinDnDClipboard",
            "com.sun.glass.ui.Window",
            "com.sun.glass.ui.View",
            "com.sun.glass.ui.Size",
            "com.sun.glass.ui.Pixels",
            "com.sun.glass.ui.Cursor",
            "com.sun.glass.ui.Clipboard",
            "com.sun.glass.ui.Application",

            "com.sun.javafx.PreviewFeature",
            "com.sun.glass.ui.win.WinPixels",
            "com.sun.glass.ui.win.WinApplication",
            "com.sun.glass.ui.Screen[]",

            "io.quarkiverse.fx.FxApplication",
            "io.quarkiverse.fx.views.FxViewConfig$$CMImpl",

            "io.quarkiverse.fx.FXMLLoaderProducer",
            "io.quarkiverse.fx.FxApplicationStartupEvent",
            "io.quarkiverse.fx.FxPostStartupEvent",
            "io.quarkiverse.fx.FxStartupLatch",
            "io.quarkiverse.fx.FxViewLoadEvent",
            "io.quarkiverse.fx.HostServicesProducer",
            "io.quarkiverse.fx.views.FxViewConfig",
            "io.quarkiverse.fx.views.FxViewRepository",
    };

    String[] JNI_RUNTIME_ACCESS_CLASSES = new String[] {
            "java.lang.Boolean",
            "java.lang.Class",
            "java.lang.Object",
            "java.lang.Runnable",
            "java.lang.String",
            "java.lang.Throwable",
            "java.util.ArrayList",
            "java.util.Collections",
            "java.util.HashMap",
            "java.util.Map",
            "javafx.scene.paint.Color",
            "com.sun.glass.ui.Application",
            "com.sun.glass.ui.Clipboard",
            "com.sun.glass.ui.Cursor",
            "com.sun.glass.ui.Pixels",
            "com.sun.glass.ui.Screen",
            "com.sun.glass.ui.Size",
            "com.sun.glass.ui.View",
            "com.sun.glass.ui.Window",
            "com.sun.glass.ui.win.WinDnDClipboard",
            "com.sun.glass.ui.win.WinGestureSupport",
            "com.sun.glass.ui.win.WinSystemClipboard",
            "com.sun.glass.ui.win.WinView",
            "com.sun.glass.ui.win.WinWindow",
            "com.sun.javafx.font.directwrite.D2D1_COLOR_F",
            "com.sun.javafx.font.directwrite.D2D1_MATRIX_3X2_F",
            "com.sun.javafx.font.directwrite.D2D1_PIXEL_FORMAT",
            "com.sun.javafx.font.directwrite.D2D1_POINT_2F",
            "com.sun.javafx.font.directwrite.D2D1_RENDER_TARGET_PROPERTIES",
            "com.sun.javafx.font.directwrite.DWRITE_GLYPH_METRICS",
            "com.sun.javafx.font.directwrite.DWRITE_GLYPH_RUN",
            "com.sun.javafx.font.directwrite.DWRITE_MATRIX",
            "com.sun.javafx.font.directwrite.DWRITE_SCRIPT_ANALYSIS",
            "com.sun.javafx.font.directwrite.RECT",
            "com.sun.prism.impl.PrismSettings",
    };

    String[] RESOURCE_BUNDLES = new String[] {
            "com.sun.javafx.scene.control.skin.resources.controls",
            "com.sun.glass.ui.win.themes",
            "com.sun.javafx.tk.quantum.QuantumMessagesBundle",
    };

    // TODO: do not include resources if the dependency is not present, specially for javafx-web which has huge library size
    String[] COMMON_RESOURCE_GLOBS = new String[] {
            "views/**/*.fxml",
            "views/**/*.properties",
            "views/**/*.css",

            "com/sun/javafx/scene/control/skin/modena/**",
            "com/sun/prism/d3d/hlsl/**",
            "com/sun/scenario/effect/impl/hw/d3d/hlsl/**",

            // .jar files in javafx-graphics
            "javafx-swt.jar",

            // Windows .dll files in javafx-graphics
            "api-ms-win-core-*.dll",
            "api-ms-win-crt-*.dll",
            "decora_sse.dll",
            "glass.dll",
            "javafx_font.dll",
            "javafx_iio.dll",
            "msvcp*.dll",
            "prism_*.dll",
            "ucrtbase.dll",
            "vcruntime*.dll",

            // Linux .so files in javafx-graphics
            "libdecora_sse.so",
            "libglass.so",
            "libglassgtk3.so",
            "libjavafx_font.so",
            "libjavafx_font_freetype.so",
            "libjavafx_font_pango.so",
            "libjavafx_iio.so",
            "libprism_common.so",
            "libprism_es2.so",
            "libprism_sw.so",

            // Mac .dylib files in javafx-graphics
            "libdecora_sse.dylib",
            "libglass.dylib",
            "libjavafx_font.dylib",
            "libjavafx_iio.dylib",
            "libprism_common.dylib",
            "libprism_es2.dylib",
            "libprism_sw.dylib",

            // Windows .dll files in javafx-media
            "fxplugins.dll",
            "glib-lite.dll",
            "gstreamer-lite.dll",
            "jfxmedia.dll",

            // Linux .so files in javafx-media
            "libavplugin-*.so",
            "libavplugin-ffmpeg-*.so",
            "libfxplugins.so",
            "libgstreamer-lite.so",
            "libjfxmedia.so",

            // Mac .dylib files in javafx-media
            "libfxplugins.dylib",
            "libglib-lite.dylib",
            "libgstreamer-lite.dylib",
            "libjfxmedia.dylib",
            "libjfxmedia_avf.dylib",

            // Windows .dll files in javafx-web
            "jfxwebkit.dll",

            // Linux .so files in javafx-web
            "libjfxwebkit.so",

            // Mac .dylib files in javafx-media
            "libjfxwebkit.dylib",
    };
}
