package io.quarkiverse.fx.showcase.pages.fxml;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;
import java.util.function.Function;
import java.util.stream.Collectors;

import jakarta.enterprise.inject.Instance;
import jakarta.inject.Inject;
import jakarta.inject.Singleton;

import io.quarkiverse.fx.showcase.core.Categories;
import io.quarkiverse.fx.showcase.core.Check;
import io.quarkiverse.fx.showcase.core.Checks;
import io.quarkiverse.fx.showcase.core.FeaturePage;
import io.quarkiverse.fx.showcase.core.Fx;
import io.quarkiverse.fx.showcase.core.MainView;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.Cursor;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.control.Button;
import javafx.scene.control.CheckBox;
import javafx.scene.control.Label;
import javafx.scene.control.MenuItem;
import javafx.scene.control.RadioButton;
import javafx.scene.control.Spinner;
import javafx.scene.control.SpinnerValueFactory;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.TextField;
import javafx.scene.control.ToggleButton;
import javafx.scene.control.ToggleGroup;
import javafx.scene.control.Tooltip;
import javafx.scene.control.TreeItem;
import javafx.scene.control.TreeView;
import javafx.scene.control.cell.TextFieldTableCell;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.shape.Rectangle;

/**
 * FXML as generated by SceneBuilder and FXMLLoader paths not covered by {@link FxmlLoaderPage} : one file per feature,
 * each one exercising a reflective path of FXMLLoader on JDK and JavaFX classes (nested class imports, {@code URL}
 * stylesheets, {@code valueOf} coercions, non-Node model classes, include bundles, a controller created by JavaFX
 * itself, boxed values, {@code java.util.HashMap} items).
 */
@Singleton
public class FxmlSceneBuilderPage implements FeaturePage {

    private static final String BUNDLE = "showcase.fxml.LoaderMessages";
    private static final String DIR = "/showcase/fxml/scenebuilder/";
    private static final String READY = "fxml-scenebuilder.ready";

    private static final double CONTENT_WIDTH = MainView.PAGE_WIDTH - 32;
    private static final double TILE_WIDTH = Math.floor((CONTENT_WIDTH - 20) / 3);
    private static final double TILE_CONTENT_WIDTH = TILE_WIDTH - 12;
    private static final double TILE_CONTENT_HEIGHT = 100;

    @Inject
    Instance<FXMLLoader> loaders;

    /**
     * @param plain loaded by a plain {@code new FXMLLoader()} instead of the CDI one
     * @param describe the check value, computed from the FXML namespace
     * @param late an optional check computed once the tile is shown (CSS applied)
     * @param lateExpected the expected value of the late check
     */
    private record Probe(String file, String title, String feature, boolean plain,
            Function<Map<String, Object>, Object> describe, Function<Map<String, Object>, Object> late,
            String lateExpected) {

        Probe(String file, String title, String feature, boolean plain, Function<Map<String, Object>, Object> describe) {
            this(file, title, feature, plain, describe, null, null);
        }
    }

    private static final List<Probe> PROBES = List.of(
            new Probe("url-stylesheet", "<URL> stylesheets",
                    "java.lang.* wildcard import, <stylesheets><URL value=\"@...\"/>, styleClass <String> list", false,
                    ns -> {
                        Parent subject = (Parent) ns.get("subject");
                        return subject.getStylesheets().stream().map(s -> s.substring(s.lastIndexOf('/') + 1)).toList()
                                + " styleClass=" + subject.getStyleClass();
                    },
                    ns -> "looked-up -sb-accent: " + ((Label) ns.get("styled")).getTextFill(),
                    "looked-up -sb-accent: 0x5e35b1ff"),
            new Probe("spinner", "Nested class imports",
                    "SpinnerValueFactory.IntegerSpinnerValueFactory / DoubleSpinnerValueFactory with @NamedArg", false,
                    ns -> {
                        @SuppressWarnings("unchecked")
                        Spinner<Integer> spinner = (Spinner<Integer>) ns.get("subject");
                        @SuppressWarnings("unchecked")
                        Spinner<Double> decimal = (Spinner<Double>) ns.get("decimal");
                        var factory = (SpinnerValueFactory.IntegerSpinnerValueFactory) spinner.getValueFactory();
                        int initial = spinner.getValue();
                        spinner.increment();
                        decimal.increment();
                        return factory.getClass().getSimpleName() + " " + factory.getMin() + ".." + factory.getMax()
                                + " step " + factory.getAmountToStepBy() + ": " + initial + " -> " + spinner.getValue()
                                + ", double 0.25 -> " + decimal.getValue() + ", '" + ((Label) ns.get("bound")).getText()
                                + "'";
                    }),
            new Probe("coercion", "valueOf coercions",
                    "accelerator=\"Shortcut+S\" (KeyCombination), showDelay=\"250ms\" (Duration), Cursor / Insets constants",
                    false,
                    ns -> {
                        MenuItem save = (MenuItem) ns.get("save");
                        MenuItem redo = (MenuItem) ns.get("redo");
                        Tooltip tip = (Tooltip) ns.get("tip");
                        Button subject = (Button) ns.get("subject");
                        ((Label) ns.get("accelerators")).setText("Save " + save.getAccelerator().getDisplayText()
                                + "   Redo " + redo.getAccelerator().getDisplayText());
                        return save.getAccelerator().getName() + " / " + redo.getAccelerator().getName() + ", tooltip "
                                + tip.getShowDelay() + " / " + tip.getHideDelay() + ", cursor "
                                + (subject.getCursor() == Cursor.HAND ? "HAND" : subject.getCursor());
                    }),
            new Probe("tree", "TreeItem model",
                    "<TreeItem value=... expanded=\"true\"> : neither a Node nor Styleable", false,
                    ns -> {
                        @SuppressWarnings("unchecked")
                        TreeView<Object> tree = (TreeView<Object>) ns.get("subject");
                        TreeItem<Object> root = tree.getRoot();
                        @SuppressWarnings("unchecked")
                        TreeItem<Object> leaf = (TreeItem<Object>) ns.get("leaf");
                        return "root '" + root.getValue() + "' expanded=" + root.isExpanded() + ", " + root.getChildren()
                                .size() + " children, " + tree.getExpandedItemCount() + " rows, leaf depth "
                                + tree.getTreeItemLevel(leaf) + " ('" + leaf.getValue() + "')";
                    }),
            new Probe("include-resources", "fx:include resources=",
                    "<fx:include resources=\"showcase.fxml.IncludeMessages\" charset=\"UTF-8\"/>", false,
                    ns -> {
                        VBox inner = (VBox) ns.get("inner");
                        return ((Label) ns.get("subject")).getText() + " | " + inner.getChildren().stream()
                                .map(n -> ((Label) n).getText()).collect(Collectors.joining(" | "));
                    }),
            new Probe("plain-controller", "Plain FXMLLoader",
                    "new FXMLLoader() : controller created by JavaFX, onAction + onValueChange handlers", true,
                    ns -> {
                        PlainController controller = (PlainController) ns.get("controller");
                        controller.button.fire();
                        controller.slider.setValue(7);
                        return controller.getClass().getSimpleName() + " initialized=" + controller.initialized + ", "
                                + String.join(", ", controller.calls);
                    }),
            new Probe("boxed-values", "Boxed values",
                    "<Integer> <Long> <Boolean> fx:value, <Double>/<Integer> fx:constant, qualified element", false,
                    ns -> {
                        Label subject = (Label) ns.get("subject");
                        Object max = ns.get("max");
                        return "cols=" + ((TextField) ns.get("field")).getPrefColumnCount() + " selected="
                                + ((CheckBox) ns.get("check")).isSelected() + " userData=" + subject.getUserData() + " ("
                                + subject.getUserData().getClass().getSimpleName() + ") maxWidth=" + subject.getMaxWidth()
                                + " max=" + max + " (" + max.getClass().getSimpleName() + "), "
                                + ns.get("qualified").getClass().getSimpleName();
                    }),
            new Probe("map-table", "HashMap + MapValueFactory",
                    "<HashMap name=... born=...> items, MapValueFactory, TextFieldTableCell fx:factory", false,
                    ns -> {
                        TableView<?> table = (TableView<?>) ns.get("subject");
                        TableColumn<?, ?> name = (TableColumn<?, ?>) ns.get("nameColumn");
                        TableColumn<?, ?> born = (TableColumn<?, ?>) ns.get("bornColumn");
                        Object cell = name.getCellFactory().call(null);
                        return table.getItems().size() + " " + table.getItems().getFirst().getClass().getSimpleName()
                                + " rows, " + name.getCellData(0) + "/" + born.getCellData(0) + ", " + name.getCellData(1)
                                + "/" + born.getCellData(1) + ", cell " + cell.getClass().getSimpleName()
                                + (cell instanceof TextFieldTableCell<?, ?> ? "" : " (unexpected)");
                    }),
            new Probe("toggle-expression", "ToggleGroup expression",
                    "fx:define <ToggleGroup>, ${group.selectedToggle.userData} walks a non-Node bean", false,
                    ns -> {
                        ToggleGroup group = (ToggleGroup) ns.get("group");
                        Label selected = (Label) ns.get("selected");
                        String before = selected.getText();
                        ((ToggleButton) ns.get("large")).setSelected(true);
                        return group.getToggles().size() + " toggles, '" + before + "' -> '" + selected.getText()
                                + "', medium selected=" + ((RadioButton) ns.get("subject")).isSelected();
                    }));

    @Override
    public String id() {
        return "fxml-scenebuilder";
    }

    @Override
    public String title() {
        return "SceneBuilder FXML & coercions";
    }

    @Override
    public String category() {
        return Categories.FXML;
    }

    @Override
    public int order() {
        return 15;
    }

    @Override
    public Node build() {
        List<Check> bundleChecks = new ArrayList<>();
        ResourceBundle bundle = FxmlUi.bundle(BUNDLE, bundleChecks, "ResourceBundle.getBundle(LoaderMessages)");
        bundleChecks.add(Checks.expect("ResourceBundle.getBundle(IncludeMessages)", "IncludeMessages bundle",
                () -> ResourceBundle.getBundle("showcase.fxml.IncludeMessages").getString("include.title")));

        GridPane grid = new GridPane(10, 10);
        List<Runnable> late = new ArrayList<>();
        int index = 0;
        for (Probe probe : PROBES) {
            grid.add(tile(probe, bundle, late), index % 3, index / 3);
            index++;
        }
        VBox intro = FxmlUi.demo("One FXML file per feature, as SceneBuilder writes them (xmlns=\"http://javafx.com/javafx/25\")."
                + " Each tile shows its check : a failure in native mode names the FXMLLoader path that broke.");
        Label bundles = FxmlUi.note(bundleChecks.stream().map(c -> (Boolean.TRUE.equals(c.ok()) ? "✔ " : "✘ ") + c.name()
                + " : " + c.value()).collect(Collectors.joining("     ")));
        intro.getChildren().add(bundles);
        Checks.attach(bundles, bundleChecks);
        intro.setPrefWidth(CONTENT_WIDTH);
        intro.setMaxWidth(CONTENT_WIDTH);

        VBox root = FxmlUi.page(10, intro, grid);
        CompletableFuture<Void> ready = FxmlLoaderPage.whenShown(root, () -> late.forEach(Runnable::run));
        root.getProperties().put(READY, ready);
        return root;
    }

    private VBox tile(Probe probe, ResourceBundle bundle, List<Runnable> late) {
        Check check;
        Node content;
        Map<String, Object> namespace = null;
        try {
            FXMLLoader loader = probe.plain() ? new FXMLLoader() : loaders.get();
            loader.setLocation(Fx.resource(DIR + probe.file() + ".fxml"));
            loader.setResources(bundle);
            content = loader.load();
            namespace = loader.getNamespace();
            Map<String, Object> ns = namespace;
            Check described = Checks.run("probe " + probe.file(), () -> probe.describe().apply(ns));
            check = new Check(described.name(), FxmlUi.sanitize(described.value()), described.ok());
        } catch (Throwable t) {
            check = Check.fail("probe " + probe.file(), FxmlUi.describe(t));
            Label error = new Label(FxmlUi.describe(t));
            error.getStyleClass().add("probe-error");
            error.setWrapText(true);
            error.setMaxWidth(TILE_CONTENT_WIDTH);
            content = error;
        }
        boolean ok = Boolean.TRUE.equals(check.ok());
        Label status = new Label(ok ? "✔" : "✘");
        status.getStyleClass().add(ok ? "probe-status-ok" : "probe-status-failed");
        Label title = new Label(probe.title() + "  ·  " + probe.file() + ".fxml");
        title.getStyleClass().add("probe-title");
        HBox header = new HBox(4, status, title);
        header.setAlignment(Pos.CENTER_LEFT);

        Label feature = FxmlUi.note(probe.feature());
        feature.setMaxWidth(TILE_CONTENT_WIDTH);

        StackPane holder = new StackPane(content);
        holder.setAlignment(Pos.TOP_LEFT);
        holder.setPrefSize(TILE_CONTENT_WIDTH, TILE_CONTENT_HEIGHT);
        holder.setMinSize(TILE_CONTENT_WIDTH, TILE_CONTENT_HEIGHT);
        holder.setMaxSize(TILE_CONTENT_WIDTH, TILE_CONTENT_HEIGHT);
        holder.setClip(new Rectangle(TILE_CONTENT_WIDTH, TILE_CONTENT_HEIGHT));

        Label value = new Label(check.value());
        value.getStyleClass().add(ok ? "probe-value" : "probe-error");
        if (ok) {
            FxmlUi.mono(value);
        }
        value.setWrapText(true);
        value.setMaxWidth(TILE_CONTENT_WIDTH);
        value.setMinHeight(javafx.scene.layout.Region.USE_PREF_SIZE);
        VBox values = new VBox(2, value);
        Checks.attach(value, List.of(check));

        VBox tile = new VBox(4, header, feature, holder, values);
        tile.getStyleClass().add("probe-tile");
        if (!ok) {
            tile.getStyleClass().add("probe-failed");
        }
        tile.setPrefWidth(TILE_WIDTH);
        tile.setMinWidth(TILE_WIDTH);
        tile.setMaxWidth(TILE_WIDTH);

        if (probe.late() != null && namespace != null) {
            Map<String, Object> ns = namespace;
            late.add(() -> {
                Check lateCheck = Checks.expect(probe.file() + " after CSS", probe.lateExpected(),
                        () -> probe.late().apply(ns));
                Label line = new Label((Boolean.TRUE.equals(lateCheck.ok()) ? "" : "✘ ") + lateCheck.value());
                line.getStyleClass().add(Boolean.TRUE.equals(lateCheck.ok()) ? "probe-value" : "probe-error");
                if (Boolean.TRUE.equals(lateCheck.ok())) {
                    FxmlUi.mono(line);
                }
                line.setWrapText(true);
                line.setMaxWidth(TILE_CONTENT_WIDTH);
                Checks.attach(line, List.of(lateCheck));
                values.getChildren().add(line);
            });
        }
        return tile;
    }

    @Override
    public CompletionStage<?> ready(Node content) {
        Object ready = content.getProperties().get(READY);
        return ready instanceof CompletionStage<?> stage ? stage : CompletableFuture.completedFuture(null);
    }
}
